apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      name: gateway-service
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: multi-cloud-k8s/gateway-server:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - name: http
      port: 8080 # Cluster-internal port
      targetPort: 8080
      nodePort: 30083 # Expose externally via NodePort for local dev
  type: NodePort # Use NodePort for easy local access via minikube ip:nodePort
      