services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: k8s_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  api:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=k8s_platform
      - MONGODB_URI=mongodb://mongodb:27017
    depends_on:
      - postgres
      - mongodb

  auth:
    build:
      context: .
      dockerfile: ./build/auth/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=k8s_platform
    depends_on:
      - postgres

volumes:
  postgres-data:
  mongodb-data:
