apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applications.unideploy.ca
spec:
  group: unideploy.ca
  names:
    kind: Application
    listKind: ApplicationList
    plural: applications
    singular: application
    shortNames:
      - app
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - image
              properties:
                image:
                  type: string
                  description: "Container image for the application"
                replicas:
                  type: integer
                  default: 1
                  minimum: 0
                  description: "Number of application replicas"
                resources:
                  type: object
                  properties:
                    cpu:
                      type: string
                      default: "100m"
                      description: "CPU resource request"
                    memory:
                      type: string
                      default: "128Mi"
                      description: "Memory resource request"
                ports:
                  type: array
                  items:
                    type: object
                    required:
                      - containerPort
                    properties:
                      name:
                        type: string
                      containerPort:
                        type: integer
                        minimum: 1
                        maximum: 65535
                      protocol:
                        type: string
                        enum:
                          - TCP
                          - UDP
                        default: TCP
                env:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                      valueFrom:
                        type: object
                        properties:
                          configMapKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                          secretKeyRef:
                            type: object
                            properties:
                              name:
                                type: string
                              key:
                                type: string
                targetClusters:
                  type: array
                  description: "List of clusters to deploy the application to"
                  items:
                    type: string
                deploymentStrategy:
                  type: string
                  enum:
                    - RollingUpdate
                    - Recreate
                    - BlueGreen
                    - Canary
                  default: RollingUpdate
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      observedGeneration:
                        type: integer
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                deployments:
                  type: array
                  items:
                    type: object
                    properties:
                      cluster:
                        type: string
                      status:
                        type: string
                      ready:
                        type: boolean
                      lastUpdated:
                        type: string
                        format: date-time
      additionalPrinterColumns:
        - name: Replicas
          type: integer
          jsonPath: .spec.replicas
        - name: Image
          type: string
          jsonPath: .spec.image
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}