apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusters.unideploy.ca
spec:
  group: unideploy.ca
  names:
    kind: Cluster
    listKind: ClusterList
    plural: clusters
    singular: cluster
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - provider
                - region
              properties:
                provider:
                  type: string
                  enum:
                    - aws
                    - gcp
                    - azure
                  description: "Cloud provider for the cluster"
                region:
                  type: string
                  description: "Region to deploy the cluster in"
                version:
                  type: string
                  description: "Kubernetes version"
                  default: "1.28"
                nodeGroups:
                  type: array
                  description: "Node groups configuration"
                  items:
                    type: object
                    required:
                      - name
                      - instanceType
                      - minSize
                      - maxSize
                    properties:
                      name:
                        type: string
                      instanceType:
                        type: string
                      minSize:
                        type: integer
                        minimum: 0
                      maxSize:
                        type: integer
                        minimum: 0
                      labels:
                        type: object
                        additionalProperties:
                          type: string
                networking:
                  type: object
                  properties:
                    vpcCidr:
                      type: string
                      pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))$'
                    subnetCidr:
                      type: string
                      pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))$'
                    serviceIpv4Cidr:
                      type: string
                      pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))$'
                authentication:
                  type: object
                  properties:
                    roleArn:
                      type: string
                    userArn:
                      type: string
            status:
              type: object
              properties:
                observedGeneration:
                  type: integer
                conditions:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - status
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum:
                          - "True"
                          - "False"
                          - "Unknown"
                      observedGeneration:
                        type: integer
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                kubeconfig:
                  type: string
                endpoint:
                  type: string
                status:
                  type: string
                  enum:
                    - Pending
                    - Creating
                    - Running
                    - Failed
                    - Deleting
                    - Deleted
      additionalPrinterColumns:
        - name: Provider
          type: string
          jsonPath: .spec.provider
        - name: Region
          type: string
          jsonPath: .spec.region
        - name: Status
          type: string
          jsonPath: .status.status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}