openapi: 3.0.3
info:
  title: Multi-Cloud Kubernetes Platform API
  description: API for managing applications and clusters across multiple cloud providers
  version: v1alpha1
  contact:
    name: Angelo Reyes
    email: angelonicolas.reyes@gmail.com
servers:
  - url: /api/v1 # This is the base path the GATEWAY exposes
    description: API base path via Gateway
paths:
  /applications:
    get:
      summary: List all applications
      operationId: listApplications
      parameters:
        - name: namespace
          in: query
          description: Kubernetes namespace
          schema:
            type: string
            default: default
        - name: label
          in: query
          description: Label selector
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Application'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Create a new application
      operationId: createApplication
      requestBody:
        description: Application to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '201':
          description: Application created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
  /applications/{name}:
    get:
      summary: Get application by name
      operationId: getApplication
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the application
          schema:
            type: string
        - name: namespace
          in: query
          description: Kubernetes namespace
          schema:
            type: string
            default: default
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
    put:
      summary: Update an application
      operationId: updateApplication
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the application
          schema:
            type: string
        - name: namespace
          in: query
          description: Kubernetes namespace
          schema:
            type: string
            default: default
      requestBody:
        description: Updated application
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Application'
      responses:
        '200':
          description: Application updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Application'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
    delete:
      summary: Delete an application
      operationId: deleteApplication
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the application
          schema:
            type: string
        - name: namespace
          in: query
          description: Kubernetes namespace
          schema:
            type: string
            default: default
      responses:
        '204':
          description: Application deleted
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalError'
  /clusters:
    get:
      summary: List all clusters
      operationId: listClusters
      parameters:
        - name: namespace
          in: query
          description: Kubernetes namespace
          schema:
            type: string
            default: default
        - name: provider
          in: query
          description: Filter by cloud provider
          schema:
            type: string
            enum: [aws, gcp, azure]
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Cluster'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Create a new cluster
      operationId: createCluster
      requestBody:
        description: Cluster to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cluster'
      responses:
        '201':
          description: Cluster created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cluster'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
  /configs:
    get:
      summary: List application configurations
      operationId: listApplicationConfigs
      tags: [ Configuration ] # (+) Add tags for grouping
      parameters:
        - name: namespace
          in: query
          description: Filter by Kubernetes namespace
          required: false
          schema:
            type: string
            default: default
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/ApplicationConfig'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/InternalError'
    post:
      summary: Create a new application configuration
      operationId: createApplicationConfig
      tags: [ Configuration ]
      requestBody:
        description: Configuration to create
        required: true
        content:
          application/json:
            schema:
              # (+) Define schema for creation (without ID, timestamps)
              type: object
              required: [ name, namespace, configData ]
              properties:
                name:
                  type: string
                  description: Name of the configuration
                namespace:
                  type: string
                  default: default
                  description: Kubernetes namespace
                configData:
                  type: object
                  description: The configuration data (JSON object)
                  example: { "key1": "value1", "replicas": 3 }
      responses:
        '201':
          description: Configuration created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationConfig'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '409':
          description: Conflict - Configuration already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          $ref: '#/components/responses/InternalError'

    /configs/{name}:
      get:
        summary: Get an application configuration by name
        operationId: getApplicationConfig
        tags: [ Configuration ]
        parameters:
          - name: name
            in: path
            required: true
            description: Name of the configuration
            schema:
              type: string
          - name: namespace
            in: query
            description: Kubernetes namespace
            required: false
            schema:
              type: string
              default: default
        responses:
          '200':
            description: Successful operation
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApplicationConfig'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '404':
            $ref: '#/components/responses/NotFound'
          '500':
            $ref: '#/components/responses/InternalError'
      put:
        summary: Update an application configuration
        operationId: updateApplicationConfig
        tags: [ Configuration ]
        parameters:
          - name: name
            in: path
            required: true
            description: Name of the configuration to update
            schema:
              type: string
          - name: namespace
            in: query
            description: Kubernetes namespace
            required: false
            schema:
              type: string
              default: default
        requestBody:
          description: Updated configuration data. Name and namespace in the body should match URL params or will be ignored.
          required: true
          content:
            application/json:
              schema:
                type: object
                required: [ configData ] # Only data needs to be in body for update usually
                properties:
                  name: # Include for clarity, but URL param takes precedence
                    type: string
                  namespace: # Include for clarity, but URL param takes precedence
                    type: string
                  configData:
                    type: object
                    description: The new configuration data (JSON object)
        responses:
          '200':
            description: Configuration updated successfully
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ApplicationConfig' # Return updated config
          '400':
            $ref: '#/components/responses/BadRequest'
          '401':
            $ref: '#/components/responses/Unauthorized'
          '404':
            $ref: '#/components/responses/NotFound'
          '500':
            $ref: '#/components/responses/InternalError'
      delete:
        summary: Delete an application configuration
        operationId: deleteApplicationConfig
        tags: [ Configuration ]
        parameters:
          - name: name
            in: path
            required: true
            description: Name of the configuration to delete
            schema:
              type: string
          - name: namespace
            in: query
            description: Kubernetes namespace
            required: false
            schema:
              type: string
              default: default
        responses:
          '204':
            description: Configuration deleted successfully
          '401':
            $ref: '#/components/responses/Unauthorized'
          '404':
            $ref: '#/components/responses/NotFound'
          '500':
            $ref: '#/components/responses/InternalError'
components:
  schemas:
    Application:
      type: object
      required:
        - metadata
        - spec
      properties:
        apiVersion:
          type: string
          default: unideploy.ca/v1alpha1
        kind:
          type: string
          default: Application
        metadata:
          type: object
          required:
            - name
          properties:
            name:
              type: string
            namespace:
              type: string
              default: default
            labels:
              type: object
              additionalProperties:
                type: string
            annotations:
              type: object
              additionalProperties:
                type: string
        spec:
          type: object
          required:
            - image
          properties:
            image:
              type: string
            replicas:
              type: integer
              default: 1
            resources:
              type: object
              properties:
                cpu:
                  type: string
                memory:
                  type: string
            ports:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  containerPort:
                    type: integer
                  protocol:
                    type: string
                    enum: [TCP, UDP]
            env:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  value:
                    type: string
            targetClusters:
              type: array
              items:
                type: string
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  message:
                    type: string
            deployments:
              type: array
              items:
                type: object
                properties:
                  cluster:
                    type: string
                  status:
                    type: string
                  ready:
                    type: boolean
    Cluster:
      type: object
      required:
        - metadata
        - spec
      properties:
        apiVersion:
          type: string
          default: unideploy.ca/v1alpha1
        kind:
          type: string
          default: Cluster
        metadata:
          type: object
          required:
            - name
          properties:
            name:
              type: string
            namespace:
              type: string
              default: default
            labels:
              type: object
              additionalProperties:
                type: string
            annotations:
              type: object
              additionalProperties:
                type: string
        spec:
          type: object
          required:
            - provider
            - region
          properties:
            provider:
              type: string
              enum: [aws, gcp, azure]
            region:
              type: string
            version:
              type: string
            nodeGroups:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  instanceType:
                    type: string
                  minSize:
                    type: integer
                  maxSize:
                    type: integer
        status:
          type: object
          properties:
            conditions:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  status:
                    type: string
                  message:
                    type: string
            endpoint:
              type: string
            status:
              type: string
              enum: [Pending, Creating, Running, Failed, Deleting, Deleted]
    ApplicationConfig:
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        name:
          type: string
          description: Name of the configuration
        namespace:
          type: string
          description: Kubernetes namespace
        userId:
          type: integer
          format: int64
          description: ID of the user who owns the config
        configData:
          type: object # Represent as JSON object in API spec
          description: Configuration data as a JSON object
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        details:
          type: string
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
tags: # (+) Add tags section
  - name: Application
    description: Application management endpoints
  - name: Cluster
    description: Cluster management endpoints
  - name: Configuration
    description: Application configuration management endpoints